# Generated by Django 5.2.14 on 2026-06-27 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('retail', 'Retail'), ('food', 'Food & Beverage'), ('transport', 'Transport'), ('utility', 'Utility'), ('health', 'Health & Pharmacy'), ('education', 'Education'), ('entertainment', 'Entertainment'), ('other', 'Other')], default='other', max_length=15)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Merchant',
                'verbose_name_plural': 'Merchants',
                'ordering': ['business_name'],
                'indexes': [models.Index(fields=['category', 'is_verified'], name='merchants_m_categor_c8e07c_idx'), models.Index(fields=['is_verified'], name='merchants_m_is_veri_a5265d_idx')],
            },
        ),
    ]
