# Generated by Django 5.2.14 on 2026-06-24 05:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_four', models.CharField(max_length=4)),
                ('card_type', models.CharField(choices=[('debit', 'Debit Card'), ('prepaid', 'Prepaid Card')], default='debit', max_length=10)),
                ('expiry_month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('expiry_year', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('blocked', 'Blocked'), ('expired', 'Expired')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='cards_card_user_id_698812_idx'), models.Index(fields=['status'], name='cards_card_status_534cb7_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('expiry_month__gte', 1), ('expiry_month__lte', 12)), name='card_valid_expiry_month')],
            },
        ),
    ]
