# Generated by Django 5.2.14 on 2026-07-29 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='_number',
            field=models.TextField(db_column='card_number', default=''),
        ),
        migrations.AddField(
            model_name='card',
            name='card_network',
            field=models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('amex', 'American Express'), ('nexus', 'Nexus')], default='visa', max_length=12),
        ),
        migrations.AddField(
            model_name='card',
            name='cardholder_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='card',
            name='masked_number',
            field=models.CharField(default='****', editable=False, max_length=19),
        ),
        migrations.AlterField(
            model_name='card',
            name='last_four',
            field=models.CharField(default='****', editable=False, max_length=4),
        ),
    ]
